### ISSUE TITLE
Metinopenbot

### ISSUE THREAD

**Issue by Bplaya** [MetinOpenBot/OpenBot#10]
I will like to know how to avoid like a game that have a cheatbloker like Gameforge in metin2. Or if you guys thinking adding it soon and and if a gm is close or some thing. Thanks. All your codes for electronic like Arduino raspberry etc are the best ever. Thank you si much

**Comment by Bloodiko** [comment]
Can you please clean this "Issue" up to 
What is the issue? 

Otherwise I will close this unnecessary "Issue"
