### ISSUE TITLE
Open with issue

### ISSUE THREAD

**Issue by ailoaieiruben** [MetinOpenBot/OpenBot#11]
I don't really know what thing do I need to open it . I might be the only one and it might not be also an issue . I have no ideea if I need an injector or what injector do I need . When I'm trying to open it it says " Open with ..... ( Notepad/Wordpad) " I can only open with those 2.

**Comment by jonathan-gtd** [comment]
Hello,

When you are on the channel selection page, you have to inject the dll eXlib.dll in the process of your metin2.
For GameForge (and a lot of Pserver) it's metin2client.exe.

So :
1- Start metin2
2- On the channel page press ALT+TAB to reduce metin2
3- Open your dll injector (i'm using DLL injector Hacker Pro v1.3.1.0, but feel free to use an other one)
Be carefull 99% of DLL injectors are detected by antivirus
4- Inject your dll (eXlib.ddl in metin2client.exe)
5- Go back to metin2, choose your channel and play.

And don't forget to close your issue if it's solved ;)

Bye

**Comment by ailoaieiruben** [comment]
Hello 

Right now it's crashing when I m injecting the DLL but I'll just figure out . 
Thank you for explaining to me anyway . 
Have a good day and happy holidays !
