### ISSUE TITLE
all reported from discord ^^

### ISSUE THREAD

**Issue by Teals53** [MetinOpenBot/OpenBot#8]
all reported from discord ^^

**Comment by alperelieyidev** [comment]
I can use EzMt2 on memoryhackers.org better than openbot

**Comment by Teals53** [comment]
it was edit my host file and broke my some software patches xd

**Comment by alperelieyidev** [comment]
It block cheatglobal.com and realitycheats.com (Scammers)

**Comment by Teals53** [comment]
and it was delete  my custom settings? and its converting that like not able to edit

**Comment by alperelieyidev** [comment]
I have not had such a problem

**Comment by Teals53** [comment]
ik already aight thx
