### ISSUE TITLE
Crashes Metin2 After 20.10.2021 Update

### ISSUE THREAD

**Issue by Kaminarifn** [MetinOpenBot/OpenBot#9]
Hello,
Metin2 got updated today (20.10.2021) and the cheat is not working anymore while injecting it crashes the game

**Comment by Lagosso** [comment]
It still works for me.

**Comment by EnryP97** [comment]
I have the same problem. Game crashes while injecting it.
Edit: the v2 version still working

**Comment by hardkid12** [comment]
> I have the same problem. Game crashes while injecting it. Edit: the v2 version still working

Where i can find de v2 version?
